# Generated by Django 6.0.3 on 2026-04-02 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usuario_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plaza',
            old_name='fechaPago',
            new_name='fechaReserva',
        ),
        migrations.RemoveField(
            model_name='plaza',
            name='pagado',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentariosRealizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plaza',
            name='pasajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trayectos', to=settings.AUTH_USER_MODEL),
        ),
    ]
